[package]
name = "catt_strict"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariadne = { version = "0.3.0", features = ["auto-color"] }
chumsky = "0.9.2"
color-eyre = "0.6.2"
derivative = "2.2.0"
eyre = "0.6.8"
itertools = "0.11.0"
thiserror = "1.0.50"
union-find = "0.4.2"
